In [7]:
import pandas as pd

# Assuming 'churn_data.csv' is in your working directory
data = pd.read_csv('/content/sample_data/Churn_Modelling.csv')

In [9]:
data.dropna(inplace=True)

In [12]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [13]:

# Assuming 'data' is your DataFrame
categorical_columns = ['Geography', 'Gender']
data_encoded = pd.get_dummies(data, columns=categorical_columns)

In [16]:


# Assuming 'data_encoded' is your DataFrame with the data and one-hot encoded categorical variables
X = data_encoded.drop(['Exited', 'Surname', 'CustomerId'], axis=1)  # Features, excluding 'Surname'
y = data_encoded['Exited']  # Target variable

# Split the data into training (80%) and testing (20%) sets with a random state for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
# Normalization is imp for fn of neural network
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20, batch_size=32, verbose=1)

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 0.4371 - accuracy: 0.8094
Epoch 2/20
250/250 [==============================] - 1s 3ms/step - loss: 0.3707 - accuracy: 0.8472
Epoch 3/20
250/250 [==============================] - 1s 3ms/step - loss: 0.3463 - accuracy: 0.8583
Epoch 4/20
250/250 [==============================] - 1s 3ms/step - loss: 0.3391 - accuracy: 0.8624
Epoch 5/20
250/250 [==============================] - 1s 2ms/step - loss: 0.3336 - accuracy: 0.8650
Epoch 6/20
250/250 [==============================] - 1s 2ms/step - loss: 0.3299 - accuracy: 0.8622
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3263 - accuracy: 0.8674
Epoch 8/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3228 - accuracy: 0.8658
Epoch 9/20
250/250 [==============================] - 1s 2ms/step - loss: 0.3203 - accuracy: 0.8673
Epoch 10/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3173 - accuracy: 0.8658
Epoch 11/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3143 - accuracy: 0.8669
Epoch 12/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3123 - accuracy: 0.8701
Epoch 13/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3093 - accuracy: 0.8704
Epoch 14/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3059 - accuracy: 0.8692
Epoch 15/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3028 - accuracy: 0.8726
Epoch 16/20
250/250 [==============================] - 0s 2ms/step - loss: 0.2997 - accuracy: 0.8751
Epoch 17/20
250/250 [==============================] - 0s 2ms/step - loss: 0.2976 - accuracy: 0.8721
Epoch 18/20
250/250 [==============================] - 0s 2ms/step - loss: 0.2956 - accuracy: 0.8776
Epoch 19/20
250/250 [==============================] - 0s 2ms/step - loss: 0.2922 - accuracy: 0.8759
Epoch 20/20
250/250 [==============================] - 0s 2ms/step - loss: 0.2894 - accuracy: 0.8760

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix

y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype(int)

accuracy = accuracy_score(y_test, y_pred_binary)
confusion = confusion_matrix(y_test, y_pred_binary)

print("Accuracy Score:", accuracy)
print("Confusion Matrix:")
print(confusion)

63/63 [==============================] - 0s 2ms/step
Accuracy Score: 0.8575
Confusion Matrix:
[[1529   78]
 [ 207  186]]

In [ ]:
# The End